server: 
  port: 12001
spring:
  application:
    name: helloWorld6
  cloud:
    services:
      registrationMethod: route    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaregistry.mybluemix.net/eureka/
  instance:
    hostname: ${CF_INSTANCE_IP:localhost}
    nonSecurePort: ${CF_INSTANCE_PORT:${PORT:${server.port:8888}}}
